"""
CLI 진입점.

사용:
    # Vertex AI 사용 (실 운영)
    export GCP_PROJECT_ID=...
    gcloud auth application-default login
    python -m agents.material_collector.run \\
        path/to/M1_4_taylorism.pdf path/to/M2_1_5_kj_method.pdf \\
        --session session_001 \\
        --out material_collector_output.json

    # Mock 모드 (단위 테스트, GCP 없이)
    python -m agents.material_collector.run \\
        path/to/lecture.pdf \\
        --mock --session test --out test.json

    # LLM 우회 (휴리스틱 fallback, 더 빠른 디버깅)
    python -m agents.material_collector.run \\
        path/to/lecture.pdf \\
        --no-llm --session test --out test.json
"""
from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path

from common.envelope import new_session_id
from common.gemini_client import GeminiClient, get_usage_summary

from agents.material_collector.agent import (
    MaterialCollector,
    MaterialCollectorConfig,
)


def _make_mock_responder():
    """Mock GeminiClient 가 쓸 stub 응답기.

    실제 LLM 응답을 흉내내기 위해 user_prompt 에서 source_file 과
    section_title 을 뽑아 그럴듯한 concept_name 을 만든다.
    """
    import re

    def responder(system_prompt: str, user_prompt: str) -> str:
        # user_prompt 에서 section_title 추출 시도
        m = re.search(r"Section title \(best guess\): (.+)", user_prompt)
        title = m.group(1).strip() if m else None

        if title and title != "(none)":
            return json.dumps(
                {
                    "concept_name": f"[mock] {title}",
                    "summary": f"This is a mock summary about '{title}'. "
                    f"In production this would be generated by Gemini.",
                    "keywords": ["mock", "stub", "concept"],
                    "is_empty": False,
                },
                ensure_ascii=False,
            )
        # title 없으면 빈 응답
        return json.dumps({"concept_name": "", "summary": "", "keywords": [], "is_empty": True})

    return responder


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Run Material Collector agent."
    )
    parser.add_argument("pdfs", nargs="+", help="강의자료 PDF 경로들")
    parser.add_argument("--session", default=None, help="session_id (없으면 자동)")
    parser.add_argument("--course", default=None, help="강의명 (기본: config)")
    parser.add_argument(
        "--out",
        default="material_collector_output.json",
        help="결과 envelope 저장 경로",
    )

    # LLM 모드
    parser.add_argument(
        "--mock", action="store_true",
        help="GeminiClient mock 모드 (GCP 없이 동작)",
    )
    parser.add_argument(
        "--no-llm", action="store_true",
        help="LLM 호출 완전 우회 (휴리스틱 fallback)",
    )

    # 파라미터
    parser.add_argument("--pages-per-chunk", type=int, default=2)
    parser.add_argument("--no-ocr", action="store_true")
    parser.add_argument("--ocr-lang", default="kor+eng")
    parser.add_argument("--ocr-dpi", type=int, default=200)
    parser.add_argument(
        "-v", "--verbose", action="store_true", help="DEBUG 로그",
    )

    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(levelname)s | %(name)s | %(message)s",
    )

    # config 조립
    cfg_kwargs: dict = {
        "pages_per_chunk": args.pages_per_chunk,
        "enable_ocr": not args.no_ocr,
        "ocr_lang": args.ocr_lang,
        "ocr_dpi": args.ocr_dpi,
        "use_llm": not args.no_llm,
    }
    if args.course:
        cfg_kwargs["course_name"] = args.course
    config = MaterialCollectorConfig(**cfg_kwargs)

    # client 조립
    if args.no_llm:
        # use_llm=False 면 client 호출이 일어나지 않지만,
        # 일단 mock 으로 둬서 instantiate 만 통과시킴
        client = GeminiClient(mock=True)
    elif args.mock:
        client = GeminiClient(mock=True, mock_responder=_make_mock_responder())
    else:
        # 실 호출 — GCP 환경 필요
        client = GeminiClient(mock=False)

    # 실행
    session_id = args.session or new_session_id()
    agent = MaterialCollector(client=client, config=config)
    env = agent.run(args.pdfs, session_id=session_id)

    # 저장
    out_path = Path(args.out)
    out_path.write_text(env.model_dump_json(indent=2), encoding="utf-8")

    # 요약 출력
    payload = env.payload
    print()
    print(f"[done] session_id   : {env.session_id}")
    print(f"       source_files : {payload['source_files']}")
    print(f"       total_pages  : {payload['total_pages']}")
    print(f"       concepts     : {payload['total_concepts']}")
    print(f"       methods      : {payload['extraction_methods']}")
    print(f"       warnings     : {len(payload['warnings'])}")
    for w in payload["warnings"][:5]:
        print(f"         - {w}")
    print(f"       saved to     : {out_path.resolve()}")

    # LLM 사용량
    usage = get_usage_summary()
    if usage["total_calls"] > 0:
        print(
            f"[llm]  calls={usage['total_calls']} tokens={usage['total_tokens']}"
        )

    return 0


if __name__ == "__main__":
    sys.exit(main())
