"""
CLI 진입점.

기본 동작:
- PDF 경로를 명령어에 직접 주면, 그 파일들을 처리한다.
- PDF 경로를 주지 않으면,
  exam_generation_system/agents/material_collector/materials/
  폴더 안의 모든 PDF를 자동으로 읽는다.

예시:

1) materials 폴더 안 모든 PDF 자동 처리
python -m agents.material_collector.run --mock --out output.json

2) 특정 PDF만 직접 지정
python -m agents.material_collector.run ./materials/M1_4.pdf --mock --out output.json

3) 다른 입력 폴더 지정
python -m agents.material_collector.run --input-dir ./somewhere --mock --out output.json

4) 하위 폴더까지 재귀적으로 PDF 탐색
python -m agents.material_collector.run --recursive --mock --out output.json
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path

from common.envelope import new_session_id
from common.gemini_client import GeminiClient, get_usage_summary
from agents.material_collector.agent import (
    MaterialCollector,
    MaterialCollectorConfig,
)


DEFAULT_MATERIALS_DIR = Path(__file__).resolve().parent / "materials"


def _make_mock_responder():
    """
    Mock GeminiClient가 쓸 stub 응답기.

    실제 LLM 응답을 흉내내기 위해 user_prompt에서 section_title을 뽑아
    그럴듯한 concept_name을 만든다.
    """
    import re

    def responder(system_prompt: str, user_prompt: str) -> str:
        m = re.search(r"Section title \(best guess\): (.+)", user_prompt)
        title = m.group(1).strip() if m else None

        if title and title != "(none)":
            return json.dumps(
                {
                    "concept_name": f"mock {title}".lower(),
                    "summary": (
                        f"This is a mock summary about '{title}'. "
                        f"In production this would be generated by Gemini."
                    ),
                    "keywords": ["mock", "stub", "concept"],
                    "is_empty": False,
                },
                ensure_ascii=False,
            )

        return json.dumps(
            {
                "concept_name": "",
                "summary": "",
                "keywords": [],
                "is_empty": True,
            },
            ensure_ascii=False,
        )

    return responder


def _collect_pdf_paths(
    explicit_pdfs: list[str],
    input_dir: Path,
    recursive: bool,
) -> list[str]:
    """
    사용자가 PDF 경로를 직접 주면 그것을 사용하고,
    아무 경로도 주지 않으면 input_dir 안의 PDF를 자동 수집한다.
    """
    if explicit_pdfs:
        return [str(Path(p)) for p in explicit_pdfs]

    if not input_dir.exists():
        raise FileNotFoundError(
            f"입력 폴더가 없습니다: {input_dir}\n"
            f"PDF 파일을 이 폴더에 넣거나, --input-dir로 다른 폴더를 지정하세요."
        )

    if not input_dir.is_dir():
        raise NotADirectoryError(f"입력 경로가 폴더가 아닙니다: {input_dir}")

    pattern = "**/*.pdf" if recursive else "*.pdf"
    pdf_paths = sorted(input_dir.glob(pattern))

    if not pdf_paths:
        raise FileNotFoundError(
            f"PDF 파일을 찾지 못했습니다: {input_dir}\n"
            f"현재 탐색 방식: {'하위 폴더 포함' if recursive else '해당 폴더만'}"
        )

    return [str(p) for p in pdf_paths]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Run Material Collector agent."
    )

    parser.add_argument(
        "pdfs",
        nargs="*",
        help=(
            "강의자료 PDF 경로들. "
            "생략하면 agents/material_collector/materials/ 안의 모든 PDF를 자동으로 읽음."
        ),
    )

    parser.add_argument(
        "--input-dir",
        default=str(DEFAULT_MATERIALS_DIR),
        help=(
            "PDF를 자동으로 찾을 입력 폴더. "
            "기본값: agents/material_collector/materials/"
        ),
    )

    parser.add_argument(
        "--recursive",
        action="store_true",
        help="input-dir 하위 폴더까지 PDF를 재귀적으로 탐색",
    )

    parser.add_argument("--session", default=None, help="session_id (없으면 자동)")
    parser.add_argument("--course", default=None, help="강의명 (기본: config)")

    parser.add_argument(
        "--out",
        default="material_collector_output.json",
        help="결과 envelope 저장 경로",
    )

    # LLM 모드
    parser.add_argument(
        "--mock",
        action="store_true",
        help="GeminiClient mock 모드 (GCP 없이 동작)",
    )

    parser.add_argument(
        "--no-llm",
        action="store_true",
        help="LLM 호출 완전 우회 (휴리스틱 fallback)",
    )

    # 파라미터
    parser.add_argument("--pages-per-chunk", type=int, default=2)
    parser.add_argument("--no-ocr", action="store_true")
    parser.add_argument("--ocr-lang", default="kor+eng")
    parser.add_argument("--ocr-dpi", type=int, default=200)

    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="DEBUG 로그",
    )

    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(levelname)s | %(name)s | %(message)s",
    )

    input_dir = Path(args.input_dir).resolve()

    try:
        pdf_paths = _collect_pdf_paths(
            explicit_pdfs=args.pdfs,
            input_dir=input_dir,
            recursive=args.recursive,
        )
    except Exception as e:
        print(f"[error] {e}", file=sys.stderr)
        return 1

    print("[input] PDF files:")
    for p in pdf_paths:
        print(f" - {p}")

    # config 조립
    cfg_kwargs: dict = {
        "pages_per_chunk": args.pages_per_chunk,
        "enable_ocr": not args.no_ocr,
        "ocr_lang": args.ocr_lang,
        "ocr_dpi": args.ocr_dpi,
        "use_llm": not args.no_llm,
    }

    if args.course:
        cfg_kwargs["course_name"] = args.course

    config = MaterialCollectorConfig(**cfg_kwargs)

    # client 조립
    if args.no_llm:
        # use_llm=False면 client 호출이 일어나지 않지만,
        # instantiate 통과를 위해 mock으로 둔다.
        client = GeminiClient(mock=True)
    elif args.mock:
        client = GeminiClient(
            mock=True,
            mock_responder=_make_mock_responder(),
        )
    else:
        # 실 호출 — GCP 환경 필요
        client = GeminiClient(mock=False)

    # 실행
    session_id = args.session or new_session_id()

    agent = MaterialCollector(
        client=client,
        config=config,
    )

    env = agent.run(pdf_paths, session_id=session_id)

    # 저장
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(env.model_dump_json(indent=2), encoding="utf-8")

    # 요약 출력
    payload = env.payload

    print()
    print(f"[done] session_id : {env.session_id}")
    print(f" source_files : {payload['source_files']}")
    print(f" total_pages  : {payload['total_pages']}")
    print(f" concepts     : {payload['total_concepts']}")
    print(f" methods      : {payload['extraction_methods']}")
    print(f" warnings     : {len(payload['warnings'])}")

    for w in payload["warnings"][:5]:
        print(f" - {w}")

    print(f" saved to     : {out_path.resolve()}")

    # LLM 사용량
    usage = get_usage_summary()
    if usage["total_calls"] > 0:
        print(
            f"[llm] calls={usage['total_calls']} "
            f"tokens={usage['total_tokens']}"
        )

    return 0


if __name__ == "__main__":
    sys.exit(main())
